### ISSUE TITLE
Integrate with ui5-next template

### ISSUE THREAD

**Issue by zouyi100** [ui5-next/ui5-redux-model#3]
Hi ui5 experts,

Can I use npm to download this module and import it as a normal npm module?

Thank you.

**Comment by Soontao** [comment]
hello,

a quick comment: current ui5-next can't import the ui5 modules by npm node_modules, because the gulp-ui5-eager-preload plugin is
not implemented the related logics to parsing/bundle ui5 modules in node_modules, I'll check it and update status next week.

thanks, have a nice day.
